name: ci_cmake

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**.F90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_cmake.yml"


jobs:

  core:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Install packages
      if: runner.os == 'linux'
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends liblapack-dev

    - name: Install packages
      if: runner.os == 'macos'
      run: brew install lapack && brew reinstall gcc

    - uses: actions/checkout@v3

    - run: cmake -B build

    - run: cmake --build build

    - run: ctest --test-dir build --preset default -V
