name: ci_cmake

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**.F90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_cmake.yml"


jobs:

  core:

    env:
      FC: gfortran-13

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: install full Lapack (linux)
      if: runner.os == 'Linux'
      run: sudo apt install liblapack-dev

    - name: install full Lapack (macos)
      if: runner.os == 'macOS'
      run: brew install lapack

    - uses: actions/checkout@v4

    - run: cmake --workflow --preset default
