name: ci_cmake

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_cmake.yml"


jobs:

  macos:
    needs: linux
    runs-on: macos-latest
    env:
        FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - run: brew install lapack

    - run: cmake -B build
    - run: cmake --build build

    - run: ctest --test-dir build


  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran g++ liblapack-dev

    - run: cmake -B build
    - run: cmake --build build

    - run: ctest --test-dir build
