name: ci_cmake

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**.F90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_cmake.yml"


jobs:

  core:

    env:
      FC: gfortran-13

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v4

    - run: cmake -B build

    - run: cmake --build build

    - run: ctest --test-dir build --preset default -V
