name: ci_meson

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**/meson.build"
      - ".github/workflows/ci_meson.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: |
        sudo apt -yq update
        sudo apt install -yq --no-install-recommends ninja-build liblapack-dev
    - run: pip install meson

    - run: meson setup build

    - run: meson compile -C build

    - run: meson test -C build

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja
    - run: brew install lapack

    - run: meson setup build
      # need all three for Meson -lgfortran
      env:
        CC: gcc-11
        CXX: g++-11
        FC: gfortran-11

    - run: meson compile -C build

    - run: meson test -C build
